### ISSUE TITLE
New Maintainers are here needed!

### ISSUE THREAD

**Issue by daviddias** [spdy-http2/node-spdy#339]
Hi everyone!

Apologies for the silence/huge delay on getting back to y'all. Unfortunately, I haven't had the chance to dedicate any time to node-spdy at all for the last year (as you might have noticed) and that translated to a bunch of PRs and issues going without response for ages, I'm sorry to everyone that has been waiting.

I want to increase the number of maintainers and I believe a way to do it is to adopt a similar strategy I created for the IPFS, libp2p and IPLD ecosystem of packages, the [Lead Maintainer Protocol](https://github.com/ipfs/community/blob/master/js-code-guidelines.md). Me and @indutny can continua acting as the tech leads and give space for new lead maintainers to appear and take ownership of getting the [4 modules of node-spdy](https://github.com/spdy-http2/) into a great shape.

Looking forward to hear your thoughts.

**Comment by coolaj86** [comment]
cc/ @anandsuresh @JeffreyAngell @jakearchibald @frank-dspeed @deveshmehta7

**Comment by coolaj86** [comment]
Also: If no one else volunteers to help maintain, I'd be interested in getting the v10.x fix merged in and adding `engines` to `package.json` so that v8.x users don't get it. I probably wouldn't make a great maintainer, but I could follow a checklist to make sure that ci passes before a merge, the new version is tagged and published, etc.

At this point (over two months seems like a long time), if someone doesn't take over to get fixes in, and if none of the 191 forks doesn't get a blessing, the project may very well... die...

So perhaps even imperfect maintainership will be better than no maintainership.

**Comment by diasdavid** [comment]
Thank you for volunteering @coolaj86! Perhaps a good solution that is today available in the Node.js community (https://changelog.com/jsparty/48 reminded me of this), is to ask for umbrella on the JS/Node.js Foundation so that this module can get proper dedicated resources.

@bnb, @dmethvin any advice on how we could make this work?

**Comment by dmethvin** [comment]
@diasdavid What sort of help are you looking for?

**Comment by diasdavid** [comment]
Maintaining the 4 modules that are on this org https://github.com/spdy-http2. They are pretty well tested and have been built for a while + SPDY and HTTP2 is a protocol that is very well spec'ed out. We could use some extra hands to ensure that the community keeps getting their PRs in.

**Comment by jimmiehansson** [comment]
Is this project still in need of maintainers?

**Comment by frank-dspeed** [comment]
@jimmiehansson i don't think so as spdy is deprecated you can now use always http2

**Comment by jimmiehansson** [comment]
@frank-dspeed Thanks. That clarifies it!

**Comment by evalsocket** [comment]
@daviddias pass me whatever help you needed  💯

**Comment by deveshmehta7** [comment]
I am willing to contribute for same.
